services:
  app:
    image: josaylin/online-learning-platform:latest   # ← במקום build: .
    container_name: online-learning-app
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/online_learning_db
      SPRING_DATASOURCE_USERNAME: yosefaylin
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: teachy-db
    environment:
      POSTGRES_DB: online_learning_db
      POSTGRES_USER: yosefaylin
      POSTGRES_PASSWORD: 123
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yosefaylin -d online_learning_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: teachy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    restart: unless-stopped

volumes:
  dbdata:
  pgadmindata:
