name: CI

on:
  push:    { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check code formatting
        run: mvn spotless:check

      - name: Build, test & coverage
        run: mvn clean verify jacoco:report

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml

      - name: Package artifact
        if: success()
        run: mvn package -DskipTests

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: OWASP Dependency Check
        if: success()
        uses: erinrose/dependency-check-action@v2
        with:
          scan-path: .
