name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn test

      - name: Build & package
        run: mvn package -DskipTests

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app-${{ matrix.java }}
          path: target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/online-learning-platform:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/online-learning-platform:${{ github.sha }}

      - name: Verify pushed image
        run: |
          echo "Image tags pushed:"
          echo " - docker.io/${{ secrets.DOCKERHUB_USERNAME }}/online-learning-platform:latest"
          echo " - docker.io/${{ secrets.DOCKERHUB_USERNAME }}/online-learning-platform:${{ github.sha }}"
